# Generated by Django 3.2.12 on 2022-05-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_students_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='message',
            new_name='messages',
        ),
    ]
