# Generated by Django 3.2.12 on 2022-05-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_message_students_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='user',
            new_name='created_by',
        ),
    ]
